### ISSUE TITLE
Schema: 'mapping > links > @type' could just be 'name', no 'source'

### ISSUE THREAD

**Issue by huonw** [data61/stellar-ingest#18]
Currently that field looks like:

```
"@type" : {
        "source" : "<some node type>",
        "name" : "<class link name>"
      }
```

where the `source` matches the source of the class link with the matching name. This was motivated by requiring class links have unique `(name, source)`, but not necessarily `name`. This is apparently deprecated and so we could change to matching the nodes: `"@type": "<class link name>"`.

**Comment by ammazza** [comment]
Closing. See comment on #20.
