### ISSUE TITLE
Schema could be versioned

### ISSUE THREAD

**Issue by huonw** [data61/stellar-ingest#20]
Currently, the scheme.json file contains information, but no version. Having a version field (possibly with a requirement that it appears first in the file, too) may make migration and schema changes easier. For instance, if we designate the current format version 1 (and a missing version field implies version == 1):

```json
{
    "version": 1,
    "sources" : [ ... ],
    ...
}
```

If we decide to rename "sources" to "files", then we can change the version and consumers can switch into version 2 mode:

```json
{
    "version": 2,
    "files" : [ ... ],
    ...
}
```

**Comment by huonw** [comment]
The versions could be http://semver.org.

**Comment by ammazza** [comment]
Thanks for the suggestion on improving the schema (this issue, #18 and #19 ). The schema needs a major re-design, which must involve all its users (ingest, UI, search/storage, possibly more in the future). It's already been discussed and it will certainly happen after Stellar releases version 0.2. I'm closing all related issues for now. I've noted them down and will get back to them when we actually start reworking the schema.

As to this particular issue, versioning is certainly needed, but I think we'll aim at something even grander, like having an extensible schema or annotations.
